name: Deployment
# deploy 전체는 작성해올것

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: set env
        working-directory: ./mock-test
        run: |
        echo PORT=${{ secrets.PORT }} > .env
        echo MESSAGE=${{ secrets.MESSAGE }} >> .env
        echo >> .env
        echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
        echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
        echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
        echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env

      - name: Install dependencies of backend
        working-directory: ./mock-test
        run: npm i
        
      - name: Run Test of backend
        working-directory: ./mock-test
        run: npm test
